[dependencies]

[package]
  cjc-version = "0.54.3"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "net_server"
  output-type = "executable"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
